<?php
/**
 * BattlePassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * BattlePassTest Class Doc Comment
 *
 * @category    Class
 * @description BattlePass
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BattlePassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BattlePass"
     */
    public function testBattlePass()
    {
    }

    /**
     * Test attribute "battle_pass_id"
     */
    public function testPropertyBattlePassId()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "battle_pass_name"
     */
    public function testPropertyBattlePassName()
    {
    }

    /**
     * Test attribute "battle_pass_description"
     */
    public function testPropertyBattlePassDescription()
    {
    }

    /**
     * Test attribute "battle_pass_short_description"
     */
    public function testPropertyBattlePassShortDescription()
    {
    }

    /**
     * Test attribute "battle_pass_disclaimer"
     */
    public function testPropertyBattlePassDisclaimer()
    {
    }

    /**
     * Test attribute "battle_pass_priority"
     */
    public function testPropertyBattlePassPriority()
    {
    }

    /**
     * Test attribute "package_sku_ios"
     */
    public function testPropertyPackageSkuIos()
    {
    }

    /**
     * Test attribute "package_sku_android"
     */
    public function testPropertyPackageSkuAndroid()
    {
    }

    /**
     * Test attribute "image_xs"
     */
    public function testPropertyImageXs()
    {
    }

    /**
     * Test attribute "image_s"
     */
    public function testPropertyImageS()
    {
    }

    /**
     * Test attribute "image_m"
     */
    public function testPropertyImageM()
    {
    }

    /**
     * Test attribute "image_l"
     */
    public function testPropertyImageL()
    {
    }

    /**
     * Test attribute "image_xl"
     */
    public function testPropertyImageXl()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "read_more_link"
     */
    public function testPropertyReadMoreLink()
    {
    }

    /**
     * Test attribute "is_unlocked_incrementally"
     */
    public function testPropertyIsUnlockedIncrementally()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "unlocked_at"
     */
    public function testPropertyUnlockedAt()
    {
    }

    /**
     * Test attribute "can_purchase_with_money"
     */
    public function testPropertyCanPurchaseWithMoney()
    {
    }

    /**
     * Test attribute "can_purchase_with_coins"
     */
    public function testPropertyCanPurchaseWithCoins()
    {
    }
}
