<?php
/**
 * BattlePassUnlockInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * BattlePassUnlockInfoTest Class Doc Comment
 *
 * @category    Class
 * @description BattlePassUnlockInfo
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BattlePassUnlockInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BattlePassUnlockInfo"
     */
    public function testBattlePassUnlockInfo()
    {
    }

    /**
     * Test attribute "purchase_id"
     */
    public function testPropertyPurchaseId()
    {
    }

    /**
     * Test attribute "battle_pass_id"
     */
    public function testPropertyBattlePassId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "purchase_price"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "purchase_currency"
     */
    public function testPropertyPurchaseCurrency()
    {
    }

    /**
     * Test attribute "purchased_at"
     */
    public function testPropertyPurchasedAt()
    {
    }

    /**
     * Test attribute "battle_pass_completed"
     */
    public function testPropertyBattlePassCompleted()
    {
    }
}
