<?php
/**
 * AppTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API to consume data structures
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * AppTest Class Doc Comment
 *
 * @category    Class
 * @description App
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "App"
     */
    public function testApp()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "app_name"
     */
    public function testPropertyAppName()
    {
    }

    /**
     * Test attribute "app_tag"
     */
    public function testPropertyAppTag()
    {
    }

    /**
     * Test attribute "app_active"
     */
    public function testPropertyAppActive()
    {
    }

    /**
     * Test attribute "app_image"
     */
    public function testPropertyAppImage()
    {
    }

    /**
     * Test attribute "app_image_hd"
     */
    public function testPropertyAppImageHd()
    {
    }

    /**
     * Test attribute "has_battle_passes"
     */
    public function testPropertyHasBattlePasses()
    {
    }

    /**
     * Test attribute "has_battle_challenges"
     */
    public function testPropertyHasBattleChallenges()
    {
    }

    /**
     * Test attribute "request_count"
     */
    public function testPropertyRequestCount()
    {
    }

    /**
     * Test attribute "rate_limit"
     */
    public function testPropertyRateLimit()
    {
    }

    /**
     * Test attribute "event_limit"
     */
    public function testPropertyEventLimit()
    {
    }

    /**
     * Test attribute "fusion_id"
     */
    public function testPropertyFusionId()
    {
    }
}
