<?php
/**
 * BattlePassLevelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * BattlePassLevelTest Class Doc Comment
 *
 * @category    Class
 * @description BattlePassLevel
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BattlePassLevelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BattlePassLevel"
     */
    public function testBattlePassLevel()
    {
    }

    /**
     * Test attribute "battle_pass_level_id"
     */
    public function testPropertyBattlePassLevelId()
    {
    }

    /**
     * Test attribute "level_priority"
     */
    public function testPropertyLevelPriority()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "can_claim"
     */
    public function testPropertyCanClaim()
    {
    }

    /**
     * Test attribute "unlocked"
     */
    public function testPropertyUnlocked()
    {
    }

    /**
     * Test attribute "claimed"
     */
    public function testPropertyClaimed()
    {
    }

    /**
     * Test attribute "reward_description"
     */
    public function testPropertyRewardDescription()
    {
    }

    /**
     * Test attribute "reward_image"
     */
    public function testPropertyRewardImage()
    {
    }

    /**
     * Test attribute "reward_image_desktop"
     */
    public function testPropertyRewardImageDesktop()
    {
    }

    /**
     * Test attribute "challenges"
     */
    public function testPropertyChallenges()
    {
    }
}
