<?php
/**
 * BattlePassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * BattlePassTest Class Doc Comment
 *
 * @category    Class
 * @description BattlePass
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BattlePassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BattlePass"
     */
    public function testBattlePass()
    {
    }

    /**
     * Test attribute "battle_pass_id"
     */
    public function testPropertyBattlePassId()
    {
    }

    /**
     * Test attribute "package_sku"
     */
    public function testPropertyPackageSku()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "truncated_description"
     */
    public function testPropertyTruncatedDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "image_desktop"
     */
    public function testPropertyImageDesktop()
    {
    }

    /**
     * Test attribute "battle_pass_start_date"
     */
    public function testPropertyBattlePassStartDate()
    {
    }

    /**
     * Test attribute "battle_pass_end_date"
     */
    public function testPropertyBattlePassEndDate()
    {
    }

    /**
     * Test attribute "read_more_link"
     */
    public function testPropertyReadMoreLink()
    {
    }

    /**
     * Test attribute "page_id"
     */
    public function testPropertyPageId()
    {
    }

    /**
     * Test attribute "battle_pass_completed"
     */
    public function testPropertyBattlePassCompleted()
    {
    }

    /**
     * Test attribute "package_value_eur"
     */
    public function testPropertyPackageValueEur()
    {
    }

    /**
     * Test attribute "purchased_at"
     */
    public function testPropertyPurchasedAt()
    {
    }

    /**
     * Test attribute "can_purchase_with_money"
     */
    public function testPropertyCanPurchaseWithMoney()
    {
    }

    /**
     * Test attribute "can_purchase_with_coins"
     */
    public function testPropertyCanPurchaseWithCoins()
    {
    }

    /**
     * Test attribute "levels"
     */
    public function testPropertyLevels()
    {
    }
}
