<?php
/**
 * ChallengeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * ChallengeTest Class Doc Comment
 *
 * @category    Class
 * @description Challenge
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChallengeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Challenge"
     */
    public function testChallenge()
    {
    }

    /**
     * Test attribute "challenge_id"
     */
    public function testPropertyChallengeId()
    {
    }

    /**
     * Test attribute "user_challenge_id"
     */
    public function testPropertyUserChallengeId()
    {
    }

    /**
     * Test attribute "challenge_name"
     */
    public function testPropertyChallengeName()
    {
    }

    /**
     * Test attribute "challenge_duration_time"
     */
    public function testPropertyChallengeDurationTime()
    {
    }

    /**
     * Test attribute "challenge_goal"
     */
    public function testPropertyChallengeGoal()
    {
    }

    /**
     * Test attribute "challenge_current_score"
     */
    public function testPropertyChallengeCurrentScore()
    {
    }

    /**
     * Test attribute "challenge_icon"
     */
    public function testPropertyChallengeIcon()
    {
    }

    /**
     * Test attribute "challenge_icon_hd"
     */
    public function testPropertyChallengeIconHd()
    {
    }

    /**
     * Test attribute "repeatable"
     */
    public function testPropertyRepeatable()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "is_claimed"
     */
    public function testPropertyIsClaimed()
    {
    }

    /**
     * Test attribute "user_challenge_unlocked_at"
     */
    public function testPropertyUserChallengeUnlockedAt()
    {
    }

    /**
     * Test attribute "user_challenge_activated_at"
     */
    public function testPropertyUserChallengeActivatedAt()
    {
    }
}
