<?php
/**
 * EventMetaDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SCILL
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SCILL;

/**
 * EventMetaDataTest Class Doc Comment
 *
 * @category    Class
 * @description This holds metadata and is specific to each event type. Please have a look at the documentation to learn which properties need to be set for the event-type you want to send.
 * @package     SCILL
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventMetaDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EventMetaData"
     */
    public function testEventMetaData()
    {
    }

    /**
     * Test attribute "action_object"
     */
    public function testPropertyActionObject()
    {
    }

    /**
     * Test attribute "action_subject"
     */
    public function testPropertyActionSubject()
    {
    }

    /**
     * Test attribute "action_type"
     */
    public function testPropertyActionType()
    {
    }

    /**
     * Test attribute "ammo_used"
     */
    public function testPropertyAmmoUsed()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "amount_gained"
     */
    public function testPropertyAmountGained()
    {
    }

    /**
     * Test attribute "amount_given"
     */
    public function testPropertyAmountGiven()
    {
    }

    /**
     * Test attribute "animal_name"
     */
    public function testPropertyAnimalName()
    {
    }

    /**
     * Test attribute "armor"
     */
    public function testPropertyArmor()
    {
    }

    /**
     * Test attribute "away_team_id"
     */
    public function testPropertyAwayTeamId()
    {
    }

    /**
     * Test attribute "away_score"
     */
    public function testPropertyAwayScore()
    {
    }

    /**
     * Test attribute "battle_status"
     */
    public function testPropertyBattleStatus()
    {
    }

    /**
     * Test attribute "bounty_name"
     */
    public function testPropertyBountyName()
    {
    }

    /**
     * Test attribute "building_id"
     */
    public function testPropertyBuildingId()
    {
    }

    /**
     * Test attribute "building_level"
     */
    public function testPropertyBuildingLevel()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "character_name"
     */
    public function testPropertyCharacterName()
    {
    }

    /**
     * Test attribute "checkpoint_id"
     */
    public function testPropertyCheckpointId()
    {
    }

    /**
     * Test attribute "coordinate_x"
     */
    public function testPropertyCoordinateX()
    {
    }

    /**
     * Test attribute "coordinate_y"
     */
    public function testPropertyCoordinateY()
    {
    }

    /**
     * Test attribute "crew_name"
     */
    public function testPropertyCrewName()
    {
    }

    /**
     * Test attribute "damage_amount"
     */
    public function testPropertyDamageAmount()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "effect_id"
     */
    public function testPropertyEffectId()
    {
    }

    /**
     * Test attribute "enemy_character"
     */
    public function testPropertyEnemyCharacter()
    {
    }

    /**
     * Test attribute "enemy_type"
     */
    public function testPropertyEnemyType()
    {
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
    }

    /**
     * Test attribute "fuel_consumed"
     */
    public function testPropertyFuelConsumed()
    {
    }

    /**
     * Test attribute "health"
     */
    public function testPropertyHealth()
    {
    }

    /**
     * Test attribute "hit_type"
     */
    public function testPropertyHitType()
    {
    }

    /**
     * Test attribute "home_team_id"
     */
    public function testPropertyHomeTeamId()
    {
    }

    /**
     * Test attribute "home_score"
     */
    public function testPropertyHomeScore()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "item_name"
     */
    public function testPropertyItemName()
    {
    }

    /**
     * Test attribute "item_type"
     */
    public function testPropertyItemType()
    {
    }

    /**
     * Test attribute "kill_type"
     */
    public function testPropertyKillType()
    {
    }

    /**
     * Test attribute "lap_position"
     */
    public function testPropertyLapPosition()
    {
    }

    /**
     * Test attribute "level_id"
     */
    public function testPropertyLevelId()
    {
    }

    /**
     * Test attribute "map_name"
     */
    public function testPropertyMapName()
    {
    }

    /**
     * Test attribute "map_section_name"
     */
    public function testPropertyMapSectionName()
    {
    }

    /**
     * Test attribute "mission_id"
     */
    public function testPropertyMissionId()
    {
    }

    /**
     * Test attribute "player_character"
     */
    public function testPropertyPlayerCharacter()
    {
    }

    /**
     * Test attribute "puzzle_id"
     */
    public function testPropertyPuzzleId()
    {
    }

    /**
     * Test attribute "race_position"
     */
    public function testPropertyRacePosition()
    {
    }

    /**
     * Test attribute "realm"
     */
    public function testPropertyRealm()
    {
    }

    /**
     * Test attribute "required_time"
     */
    public function testPropertyRequiredTime()
    {
    }

    /**
     * Test attribute "resource_gained"
     */
    public function testPropertyResourceGained()
    {
    }

    /**
     * Test attribute "resource_given"
     */
    public function testPropertyResourceGiven()
    {
    }

    /**
     * Test attribute "resource_name"
     */
    public function testPropertyResourceName()
    {
    }

    /**
     * Test attribute "round_id"
     */
    public function testPropertyRoundId()
    {
    }

    /**
     * Test attribute "round_type"
     */
    public function testPropertyRoundType()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "stat_type"
     */
    public function testPropertyStatType()
    {
    }

    /**
     * Test attribute "time_condition"
     */
    public function testPropertyTimeCondition()
    {
    }

    /**
     * Test attribute "transport_id"
     */
    public function testPropertyTransportId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "unit_type"
     */
    public function testPropertyUnitType()
    {
    }

    /**
     * Test attribute "upgrade_type"
     */
    public function testPropertyUpgradeType()
    {
    }

    /**
     * Test attribute "weapon_action"
     */
    public function testPropertyWeaponAction()
    {
    }

    /**
     * Test attribute "weapon_id"
     */
    public function testPropertyWeaponId()
    {
    }

    /**
     * Test attribute "weapon_type"
     */
    public function testPropertyWeaponType()
    {
    }

    /**
     * Test attribute "weapon_used"
     */
    public function testPropertyWeaponUsed()
    {
    }

    /**
     * Test attribute "zone_name"
     */
    public function testPropertyZoneName()
    {
    }
}
